/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EffortLevel = "high" | "low" | "max" | "medium" | "xhigh";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface _Migrations {
  applied_at: Generated<import('dayjs').Dayjs>;
  name: string;
}

export interface AppSettings {
  chat_model: string;
  effort: EffortLevel;
  id: Generated<boolean>;
}

export interface ChannelSettings {
  channel_id: string;
  created_at: Generated<import('dayjs').Dayjs>;
  ephemeral: Generated<boolean>;
  muted: Generated<boolean>;
  updated_at: Generated<import('dayjs').Dayjs>;
}

export interface Memory {
  as_of: import('dayjs').Dayjs;
  channel_id: string;
  content: string;
  created_at: Generated<import('dayjs').Dayjs>;
  updated_at: Generated<import('dayjs').Dayjs>;
}

export interface Messages {
  channel_id: string;
  content: string;
  created_at: Generated<import('dayjs').Dayjs>;
  id: string;
  kind: Generated<string>;
  sent_at: import('dayjs').Dayjs;
  user_id: string;
  user_name: string;
}

export interface Reminders {
  channel_id: string | null;
  content: string;
  created_at: Generated<import('dayjs').Dayjs>;
  date: import('dayjs').Dayjs;
  id: Generated<string>;
  received: Generated<boolean>;
  status: Generated<string>;
  target: string | null;
}

export interface ToolLog {
  channel_id: string;
  created_at: Generated<import('dayjs').Dayjs>;
  duration_ms: number;
  error: string | null;
  id: Generated<Int8>;
  in_reply_to: string | null;
  input: Json;
  output: string | null;
  tool: string;
}

export interface Usage {
  cache_read_input_tokens: number;
  created_at: Generated<import('dayjs').Dayjs>;
  effort: string;
  id: Generated<Int8>;
  in_reply_to: string | null;
  input_tokens: number;
  model: string;
  output_tokens: number;
}

export interface DB {
  _migrations: _Migrations;
  app_settings: AppSettings;
  channel_settings: ChannelSettings;
  memory: Memory;
  messages: Messages;
  reminders: Reminders;
  tool_log: ToolLog;
  usage: Usage;
}
