/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _Migrations {
  applied_at: Generated<Timestamp>;
  name: string;
}

export interface AgentSettings {
  channel_id: string;
  created_at: Generated<Timestamp>;
  memory: Generated<string>;
  model: string | null;
  system_prompt: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Messages {
  channel_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  id: string;
  sent_at: Timestamp;
  thread_id: string | null;
  user_id: string;
  user_name: string;
}

export interface DB {
  _migrations: _Migrations;
  agent_settings: AgentSettings;
  messages: Messages;
}
