/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EffortLevel = "high" | "low" | "max" | "medium" | "xhigh";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _Migrations {
  applied_at: Generated<Timestamp>;
  name: string;
}

export interface AppSettings {
  id: Generated<boolean>;
  reminder_channel_id: string | null;
}

export interface ChannelSettings {
  channel_id: string;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  effort: EffortLevel | null;
  ephemeral: Generated<boolean>;
  memory: Generated<string>;
  model: string | null;
  system_prompt: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Messages {
  channel_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  id: string;
  kind: Generated<string>;
  sent_at: Timestamp;
  user_id: string;
  user_name: string;
}

export interface Reminders {
  channel_id: string | null;
  content: string;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<string>;
  received: Generated<boolean>;
  status: Generated<string>;
  target: string | null;
}

export interface Usage {
  cache_creation_input_tokens: number;
  cache_read_input_tokens: number;
  created_at: Generated<Timestamp>;
  effort: string;
  id: Generated<Int8>;
  in_reply_to: string | null;
  input_tokens: number;
  model: string;
  output_tokens: number;
}

export interface DB {
  _migrations: _Migrations;
  app_settings: AppSettings;
  channel_settings: ChannelSettings;
  messages: Messages;
  reminders: Reminders;
  usage: Usage;
}
